/**
 * Check every claim in a published write-up against the database.
 *
 *   npm run audit:writeups -- 2026-08-28
 *
 * Every error found in these files so far has been the same shape: a sentence
 * generated by a rule, asserting something the data does not support. Reading
 * them by eye caught four in an evening; this catches the class.
 *
 * It reads the file that actually went out, extracts the factual claims, and
 * tests each against the runner's record. It does not check the opinion — only
 * whether the stated facts are true.
 */
import "dotenv/config";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import postgres from "postgres";
import { readComment } from "../lib/form-reading";
import { writeUpsPath } from "../lib/published";
import { OUT_DIR } from "../lib/published";

type Fault = { race: string; horse: string; claim: string; problem: string };

const norm = (s: string) => s.toUpperCase().replace(/[^A-Z0-9]/g, "");

(async () => {
  const date = process.argv[2];
  if (!date || !/^\d{4}-\d{2}-\d{2}$/.test(date)) {
    console.error("usage: npm run audit:writeups -- YYYY-MM-DD");
    process.exit(1);
  }

  // Use the shared resolver rather than rebuilding the filename here. The
  // daily report renames these files ("MONDAY 31 August - RACE WRITE-UPS.txt")
  // and this auditor was still looking for the old convention, so it had been
  // failing to open anything at all rather than reporting no faults.
  const path = writeUpsPath(date);
  if (!path) {
    console.error(`no write-ups file found for ${date}`);
    process.exit(1);
  }
  const lines = readFileSync(path, "utf8").split(/\r?\n/);

  // Pull the selection sentence out of each race.
  type Claim = { race: string; horse: string; sentence: string };
  const claims: Claim[] = [];
  let race = "";

  for (const l of lines) {
    const r = l.match(/^(\d{2}:\d{2})\s{2,}(.+)$/);
    if (r) { race = `${r[1]} ${r[2].slice(0, 40)}`; continue; }

    // "HORSE NAME at 12/5, Trainer and Jockey, makes most appeal. It ..."
    const m = l.match(/^([A-Z][A-Z0-9' ]+[A-Z0-9]) at .*?(?:makes most appeal|looks the pick of these|is the one[^.]*)\.\s*(.*)$/);
    if (m) claims.push({ race, horse: m[1].trim(), sentence: m[2] });
  }

  // The NAP note is a separate file and was never audited — which is exactly
  // where the Cosmos Raj contradiction lived. The biggest bet of the day was
  // the one piece of prose nothing was checking.
  const selfContradicting: string[] = [];
  const dir = OUT_DIR;
  for (const f of readdirSync(dir)) {
    if (!f.startsWith(`${date} VIP `) || !f.endsWith(".txt")) continue;
    const body = readFileSync(join(dir, f), "utf8");

    // A note that opens as the play and signs off telling the reader not to
    // back it is broken whatever else it says.
    //
    // Dan, 2026-09-08, on Lucky Hero: "I'm a little concerned on tomorrow's NAP
    // write-up, very negative ending — especially for a NAP." The note argued
    // the horse up in paragraph one, argued it down in paragraph two, and
    // signed off "NOT A NAP — one to watch rather than back" on the strongest
    // bet of the day. Every existing check passed it, because each one looks
    // for a claim the record does not support and none of them read the note
    // as a whole.
    if (/^NOT A (?:NAP|VIP PLAY) —/m.test(body)) {
      selfContradicting.push(
        `${f.replace(`${date} VIP `, "").replace(".txt", "")} — the note signs off ` +
        `"NOT A ${/^NOT A (NAP|VIP PLAY)/m.exec(body)?.[1]}" on the day's own selection`
      );
    }

    const horse = (body.match(/^VIP PLAY — .*? — ([A-Z][A-Z' ]+) —/m) ?? [])[1];
    if (!horse) continue;
    // The whole note is one claim: a contradiction anywhere in it is a
    // contradiction.
    claims.push({
      race: `NAP note — ${f.replace(`${date} VIP `, "").replace(".txt", "")}`,
      horse: horse.trim(),
      sentence: body.replace(/\s+/g, " "),
    });
  }

  const sql = postgres(process.env.DATABASE_URL!, { ssl: "require" });

  const runners = await sql`
    select r.horse_id, r.horse_name
    from runners r join races ra on ra.id = r.race_id
    where ra.race_date = ${date} and r.is_non_runner = false`;

  const idByName = new Map<string, string>();
  for (const r of runners as any[]) idByName.set(norm(r.horse_name), r.horse_id);

  const faults: Fault[] = [];
  let checked = 0;

  for (const c of claims) {
    const id = idByName.get(norm(c.horse));
    if (!id) {
      faults.push({ ...c, claim: "—", problem: "named horse is not a declared runner in this race" });
      continue;
    }

    const history = await sql`
      select ra.race_date, r.position_num, r.ofr, r.comment, r.ovr_btn
      from runners r join races ra on ra.id = r.race_id
      where r.horse_id = ${id} and ra.race_date < ${date} and r.position_num is not null
      order by ra.race_date desc limit 20`;

    const runs = history as any[];
    const last = runs[0];
    checked++;

    // 1. "was staying on at the finish last time" — the comment must support it.
    if (/staying on at the finish last time/.test(c.sentence)) {
      if (!last?.comment) {
        faults.push({ ...c, claim: "staying on last time", problem: "no comment on the last run to support it" });
      } else if (!readComment(last.comment).stayedOn) {
        faults.push({ ...c, claim: "staying on last time", problem: `comment does not support it: "${String(last.comment).slice(-70)}"` });
      }
    }

    // 2. A win last time is the biggest fact about a horse. If it won and the
    //    sentence leads on a beaten run instead, that is the Box Clever error.
    if (last?.position_num === 1 && /^It was beaten /.test(c.sentence)) {
      faults.push({ ...c, claim: "leads on a beaten run", problem: `won last time out (${String(last.race_date).slice(0, 10)}) — that should lead` });
    }

    // 3. "beaten NL off M" must match a real run.
    const btn = c.sentence.match(/beaten ([\d.]+) lengths? off (\d+)/);
    if (btn) {
      const [, lenS, ofrS] = btn;
      const hit = runs.some(
        (r) => String(r.ofr) === ofrS && Math.abs(Number(r.ovr_btn ?? -1) - Number(lenS)) < 0.6
      );
      if (!hit) faults.push({ ...c, claim: btn[0], problem: "no run in the record matches that mark and margin" });
    }

    // 4. "has won here N times" must match the course record.
    const here = c.sentence.match(/has won here(?: (\d+) times| twice)?/);
    if (here) {
      const claimed = here[1] ? parseInt(here[1], 10) : here[0].includes("twice") ? 2 : 1;
      const [row] = await sql`
        select count(*)::int n
        from runners r join races ra on ra.id = r.race_id
        where r.horse_id = ${id} and r.position_num = 1 and ra.race_date < ${date}
          and ra.course_slug = (
            select course_slug from races where race_date = ${date}
              and id = (select race_id from runners where horse_id = ${id}
                        and race_id in (select id from races where race_date = ${date}) limit 1))`;
      if ((row as any).n !== claimed)
        faults.push({ ...c, claim: here[0], problem: `record shows ${(row as any).n} course win(s)` });
    }

    // 5. Grammar that has bitten before.
    if (/\b1 lengths\b/.test(c.sentence))
      faults.push({ ...c, claim: "1 lengths", problem: "singular/plural" });

    // 6. The write-up must not argue against the horse's own last run.
    //
    // Dan, 2026-09-01: "these write-ups don't make any sense — he won the last
    // race", then "we need to check all write-ups, this can't happen, it's
    // sloppy."
    //
    // The Cosmos Raj NAP opened "you can pretty much draw a line through the
    // last couple of runs because he just hasn't looked quite at the top of
    // his game" about a horse that had just won, and closed asking it to "find
    // a bit more than he has shown". Every one of those phrases was generated
    // from a count of the last THREE runs, which cannot see that the most
    // recent was a win.
    //
    // Checking the phrases is what makes this stay fixed. The generator can be
    // corrected in one place and re-break somewhere else; a horse that won and
    // a sentence that says it did not is a contradiction wherever it appears.
    const lastRun = (history as any[])[0];
    const lastPos = lastRun ? Number(lastRun.position_num) : null;

    if (lastPos === 1) {
      const dismissals: [RegExp, string][] = [
        [/draw a line through/i, "dismisses recent form"],
        [/hasn'?t looked quite at the top of his game/i, "says he is out of sorts"],
        [/find a bit more than he has shown/i, "asks him to improve on a win"],
        [/if the spark comes back/i, "doubts his form"],
        [/wouldn'?t be writing him off/i, "defends a horse that needs no defending"],
        [/\bwas (?:well )?beaten\b/i, "says he was beaten"],
        [/finished won/i, "ungrammatical: a win rendered as a finishing position"],
      ];
      for (const [re, why] of dismissals) {
        const m = c.sentence.match(re);
        if (m) faults.push({ ...c, claim: m[0], problem: `${why} — he WON last time` });
      }
    }

    // A horse placed last time is not "out of sorts" either, though it may
    // fairly be asked for more.
    if (lastPos !== null && lastPos > 1 && lastPos <= 3) {
      const m = c.sentence.match(/draw a line through the last (?:couple of )?runs?/i);
      if (m) faults.push({ ...c, claim: m[0], problem: `dismisses a run he finished ${lastPos}${lastPos === 2 ? "nd" : "rd"} in` });
    }

    // 7. Pronoun and auxiliary breaks from the phrase joiner.
    for (const [re, why] of [
      [/\bhe ridden\b/i, "missing auxiliary: 'he ridden'"],
      [/\bhe he\b/i, "doubled pronoun"],
      [/\band won and\b/i, "doubled conjunction"],
      [/\bwas was\b/i, "doubled auxiliary"],
    ] as [RegExp, string][]) {
      const m = c.sentence.match(re);
      if (m) faults.push({ ...c, claim: m[0], problem: why });
    }
  }

  console.log(`\nWRITE-UP AUDIT — ${date}`);
  console.log("=".repeat(78));
  console.log(`  ${checked} selections checked\n`);

  if (selfContradicting.length) {
    console.log(`  ${selfContradicting.length} note${selfContradicting.length === 1 ? "" : "s"} that argue against their own selection:\n`);
    for (const n of selfContradicting) console.log(`    ${n}\n`);
  }

  if (!faults.length && !selfContradicting.length) {
    console.log("  No unsupported claims found.\n");
  } else if (!faults.length) {
    // nothing else to add
  } else {
    console.log(`  ${faults.length} problem${faults.length === 1 ? "" : "s"}:\n`);
    for (const f of faults) {
      console.log(`  ${f.race}`);
      console.log(`    ${f.horse} — ${f.claim}`);
      console.log(`    ${f.problem}\n`);
    }
  }

  await sql.end();
  process.exit(faults.length || selfContradicting.length ? 1 : 0);
})();
